 
var emojisTextures = [
"images/Selected/emoji-0.png",
"images/Selected/emoji-1.png",
"images/Selected/emoji-2.png",
"images/Selected/emoji-3.png",
"images/Selected/emoji-4.png",
"images/Selected/emoji-5.png",
"images/Selected/emoji-6.png",
"images/Selected/emoji-7.png",
"images/Selected/emoji-8.png",
"images/Selected/emoji-9.png",
"images/Selected/emoji-10.png",
"images/Selected/emoji-11.png",
"images/Selected/emoji-12.png",
"images/Selected/emoji-13.png",
"images/Selected/emoji-14.png",
"images/Selected/emoji-15.png",
"images/Selected/emoji-16.png",
"images/Selected/emoji-17.png",
"images/Selected/emoji-18.png",
"images/Selected/emoji-19.png",
"images/Selected/emoji-20.png",
"images/Selected/emoji-21.png",
"images/Selected/emoji-22.png",
"images/Selected/emoji-23.png",
"images/Selected/emoji-24.png",
"images/Selected/emoji-25.png",
"images/Selected/emoji-26.png",
"images/Selected/emoji-27.png",
"images/Selected/emoji-28.png",
"images/Selected/emoji-29.png",
"images/Selected/emoji-30.png",
"images/Selected/emoji-31.png",
"images/Selected/emoji-32.png",
"images/Selected/emoji-33.png",
"images/Selected/emoji-34.png",
"images/Selected/emoji-35.png",
"images/Selected/emoji-36.png",
"images/Selected/emoji-37.png",
"images/Selected/emoji-38.png",
"images/Selected/emoji-39.png",
"images/Selected/emoji-40.png",
"images/Selected/emoji-41.png",
"images/Selected/emoji-42.png",
"images/Selected/emoji-43.png",
"images/Selected/emoji-44.png",
"images/Selected/emoji-45.png",
"images/Selected/emoji-46.png",
"images/Selected/emoji-47.png",
"images/Selected/emoji-48.png",
"images/Selected/emoji-49.png",
"images/Selected/emoji-50.png",
"images/Selected/emoji-51.png",
"images/Selected/emoji-52.png",
"images/Selected/emoji-53.png",
"images/Selected/emoji-54.png",
"images/Selected/emoji-55.png",
"images/Selected/emoji-56.png",
"images/Selected/emoji-57.png",
"images/Selected/emoji-58.png",
"images/Selected/emoji-59.png",
"images/Selected/emoji-60.png",
"images/Selected/emoji-61.png",
"images/Selected/emoji-62.png",
"images/Selected/emoji-63.png",
"images/Selected/emoji-64.png",
"images/Selected/emoji-65.png",
"images/Selected/emoji-66.png",
"images/Selected/emoji-67.png",
"images/Selected/emoji-68.png",
"images/Selected/emoji-69.png",
"images/Selected/emoji-70.png",
"images/Selected/emoji-71.png",
"images/Selected/emoji-72.png",
"images/Selected/emoji-73.png",
"images/Selected/emoji-74.png",
"images/Selected/emoji-75.png",
"images/Selected/emoji-76.png",
"images/Selected/emoji-77.png",
"images/Selected/emoji-78.png",
"images/Selected/emoji-79.png",
"images/Selected/emoji-80.png",
"images/Selected/emoji-81.png",
"images/Selected/emoji-82.png",
"images/Selected/emoji-83.png",
"images/Selected/emoji-84.png",
"images/Selected/emoji-85.png",
"images/Selected/emoji-86.png",
"images/Selected/emoji-87.png",
"images/Selected/emoji-88.png",
"images/Selected/emoji-89.png"
// "images/Selected/emoji-90.png",
// "images/Selected/emoji-91.png",
// "images/Selected/emoji-92.png",
// "images/Selected/emoji-93.png",
// "images/Selected/emoji-94.png",
// "images/Selected/emoji-95.png",
// "images/Selected/emoji-96.png",
// "images/Selected/emoji-97.png",
// "images/Selected/emoji-98.png",
// "images/Selected/emoji-99.png",
// "images/Selected/emoji-100.png",
// "images/Selected/emoji-101.png",
// "images/Selected/emoji-102.png",
// "images/Selected/emoji-103.png",
// "images/Selected/emoji-104.png",
// "images/Selected/emoji-105.png",
// "images/Selected/emoji-106.png",
// "images/Selected/emoji-107.png",
// "images/Selected/emoji-108.png",
// "images/Selected/emoji-109.png",
// "images/Selected/emoji-110.png",
// "images/Selected/emoji-111.png",
// "images/Selected/emoji-112.png",
// "images/Selected/emoji-113.png",
// "images/Selected/emoji-114.png",
// "images/Selected/emoji-115.png",
// "images/Selected/emoji-116.png",
// "images/Selected/emoji-117.png",
// "images/Selected/emoji-118.png",
// "images/Selected/emoji-119.png",
// "images/Selected/emoji-120.png",
// "images/Selected/emoji-121.png",
// "images/Selected/emoji-122.png",
// "images/Selected/emoji-123.png",
// "images/Selected/emoji-124.png",
// "images/Selected/emoji-125.png",
// "images/Selected/emoji-126.png",
// "images/Selected/emoji-127.png",
// "images/Selected/emoji-128.png",
// "images/Selected/emoji-129.png",
// "images/Selected/emoji-130.png",
// "images/Selected/emoji-131.png",
// "images/Selected/emoji-132.png",
// "images/Selected/emoji-133.png",
// "images/Selected/emoji-134.png",
// "images/Selected/emoji-135.png",
// "images/Selected/emoji-136.png",
// "images/Selected/emoji-137.png",
// "images/Selected/emoji-138.png",
// "images/Selected/emoji-139.png",
// "images/Selected/emoji-140.png",
// "images/Selected/emoji-141.png",
// "images/Selected/emoji-142.png",
// "images/Selected/emoji-143.png",
// "images/Selected/emoji-144.png",
// "images/Selected/emoji-145.png",
// "images/Selected/emoji-146.png",
// "images/Selected/emoji-147.png",
// "images/Selected/emoji-148.png",
// "images/Selected/emoji-149.png",
// "images/Selected/emoji-150.png",
// "images/Selected/emoji-151.png",
// "images/Selected/emoji-152.png",
// "images/Selected/emoji-153.png",
// "images/Selected/emoji-154.png",
// "images/Selected/emoji-155.png",
// "images/Selected/emoji-156.png",
// "images/Selected/emoji-157.png",
// "images/Selected/emoji-158.png",
// "images/Selected/emoji-159.png",
// "images/Selected/emoji-160.png",
// "images/Selected/emoji-161.png",
// "images/Selected/emoji-162.png",
// "images/Selected/emoji-163.png",
// "images/Selected/emoji-164.png",
// "images/Selected/emoji-165.png",
// "images/Selected/emoji-166.png",
// "images/Selected/emoji-167.png",
// "images/Selected/emoji-168.png",
// "images/Selected/emoji-169.png",
// "images/Selected/emoji-170.png",
// "images/Selected/emoji-171.png",
// "images/Selected/emoji-172.png",
// "images/Selected/emoji-173.png",
// "images/Selected/emoji-174.png",
// "images/Selected/emoji-175.png",
// "images/Selected/emoji-176.png",
// "images/Selected/emoji-177.png",
// "images/Selected/emoji-178.png",
// "images/Selected/emoji-179.png",
// "images/Selected/emoji-180.png",
// "images/Selected/emoji-181.png",
// "images/Selected/emoji-182.png",
// "images/Selected/emoji-183.png",
// "images/Selected/emoji-184.png",
// "images/Selected/emoji-185.png",
// "images/Selected/emoji-186.png",
// "images/Selected/emoji-187.png",
// "images/Selected/emoji-188.png",
// "images/Selected/emoji-189.png",
// "images/Selected/emoji-190.png",
// "images/Selected/emoji-191.png",
// "images/Selected/emoji-192.png",
// "images/Selected/emoji-193.png",
// "images/Selected/emoji-194.png",
// "images/Selected/emoji-195.png",
// "images/Selected/emoji-196.png",
// "images/Selected/emoji-197.png",
// "images/Selected/emoji-198.png",
// "images/Selected/emoji-199.png",
// "images/Selected/emoji-200.png",
// "images/Selected/emoji-201.png",
// "images/Selected/emoji-202.png",
// "images/Selected/emoji-203.png",
// "images/Selected/emoji-204.png",
// "images/Selected/emoji-205.png",
// "images/Selected/emoji-206.png",
// "images/Selected/emoji-207.png",
// "images/Selected/emoji-208.png",
// "images/Selected/emoji-209.png",
// "images/Selected/emoji-210.png",
// "images/Selected/emoji-211.png",
// "images/Selected/emoji-212.png",
// "images/Selected/emoji-213.png",
// "images/Selected/emoji-214.png",
// "images/Selected/emoji-215.png",
// "images/Selected/emoji-216.png",
// "images/Selected/emoji-217.png",
// "images/Selected/emoji-218.png",
// "images/Selected/emoji-219.png",
// "images/Selected/emoji-220.png",
// "images/Selected/emoji-221.png",
// "images/Selected/emoji-222.png",
// "images/Selected/emoji-223.png",
// "images/Selected/emoji-224.png",
// "images/Selected/emoji-225.png",
// "images/Selected/emoji-226.png",
// "images/Selected/emoji-227.png",
// "images/Selected/emoji-228.png",
// "images/Selected/emoji-229.png",
// "images/Selected/emoji-230.png",
// "images/Selected/emoji-231.png",
// "images/Selected/emoji-232.png",
// "images/Selected/emoji-233.png",
// "images/Selected/emoji-234.png",
// "images/Selected/emoji-235.png",
// "images/Selected/emoji-236.png",
// "images/Selected/emoji-237.png",
// "images/Selected/emoji-238.png",
// "images/Selected/emoji-239.png",
// "images/Selected/emoji-240.png",
// "images/Selected/emoji-241.png",
// "images/Selected/emoji-242.png",
// "images/Selected/emoji-243.png",
// "images/Selected/emoji-244.png",
// "images/Selected/emoji-245.png",
// "images/Selected/emoji-246.png",
// "images/Selected/emoji-247.png",
// "images/Selected/emoji-248.png",
// "images/Selected/emoji-249.png",
// "images/Selected/emoji-250.png",
// "images/Selected/emoji-251.png",
// "images/Selected/emoji-252.png",
// "images/Selected/emoji-253.png",
// "images/Selected/emoji-254.png",
// "images/Selected/emoji-255.png",
// "images/Selected/emoji-256.png",
// "images/Selected/emoji-257.png",
// "images/Selected/emoji-258.png",
// "images/Selected/emoji-259.png",
// "images/Selected/emoji-260.png",
// "images/Selected/emoji-261.png",
// "images/Selected/emoji-262.png",
// "images/Selected/emoji-263.png",
// "images/Selected/emoji-264.png",
// "images/Selected/emoji-265.png",
// "images/Selected/emoji-266.png",
// "images/Selected/emoji-267.png",
// "images/Selected/emoji-268.png",
// "images/Selected/emoji-269.png",
// "images/Selected/emoji-270.png",
// "images/Selected/emoji-271.png",
// "images/Selected/emoji-272.png",
// "images/Selected/emoji-273.png",
// "images/Selected/emoji-274.png",
// "images/Selected/emoji-275.png",
// "images/Selected/emoji-276.png",
// "images/Selected/emoji-277.png",
// "images/Selected/emoji-278.png",
// "images/Selected/emoji-279.png",
// "images/Selected/emoji-280.png",
// "images/Selected/emoji-281.png",
// "images/Selected/emoji-282.png",
// "images/Selected/emoji-283.png",
// "images/Selected/emoji-284.png",
// "images/Selected/emoji-285.png",
// "images/Selected/emoji-286.png",
// "images/Selected/emoji-287.png",
// "images/Selected/emoji-288.png",
// "images/Selected/emoji-289.png",
// "images/Selected/emoji-290.png",
// "images/Selected/emoji-291.png",
// "images/Selected/emoji-292.png",
// "images/Selected/emoji-293.png",
// "images/Selected/emoji-294.png",
// "images/Selected/emoji-295.png",
// "images/Selected/emoji-296.png",
// "images/Selected/emoji-297.png",
// "images/Selected/emoji-298.png",
// "images/Selected/emoji-299.png",
// "images/Selected/emoji-300.png",
// "images/Selected/emoji-301.png",
// "images/Selected/emoji-302.png",
// "images/Selected/emoji-303.png",
// "images/Selected/emoji-304.png",
// "images/Selected/emoji-305.png",
// "images/Selected/emoji-306.png",
// "images/Selected/emoji-307.png",
// "images/Selected/emoji-308.png",
// "images/Selected/emoji-309.png",
// "images/Selected/emoji-310.png",
// "images/Selected/emoji-311.png",
// "images/Selected/emoji-312.png",
// "images/Selected/emoji-313.png",
// "images/Selected/emoji-314.png",
// "images/Selected/emoji-315.png",
// "images/Selected/emoji-316.png",
// "images/Selected/emoji-317.png",
// "images/Selected/emoji-318.png",
// "images/Selected/emoji-319.png",
// "images/Selected/emoji-320.png",
// "images/Selected/emoji-321.png",
// "images/Selected/emoji-322.png",
// "images/Selected/emoji-323.png",
// "images/Selected/emoji-324.png",
// "images/Selected/emoji-325.png",
// "images/Selected/emoji-326.png",
// "images/Selected/emoji-327.png",
// "images/Selected/emoji-328.png",
// "images/Selected/emoji-329.png",
// "images/Selected/emoji-330.png",
// "images/Selected/emoji-331.png",
// "images/Selected/emoji-332.png",
// "images/Selected/emoji-333.png",
// "images/Selected/emoji-334.png",
// "images/Selected/emoji-335.png",
// "images/Selected/emoji-336.png",
// "images/Selected/emoji-337.png",
// "images/Selected/emoji-338.png",
// "images/Selected/emoji-339.png",
// "images/Selected/emoji-340.png",
// "images/Selected/emoji-341.png",
// "images/Selected/emoji-342.png",
// "images/Selected/emoji-343.png",
// "images/Selected/emoji-344.png",
// "images/Selected/emoji-345.png",
// "images/Selected/emoji-346.png",
// "images/Selected/emoji-347.png",
// "images/Selected/emoji-348.png",
// "images/Selected/emoji-349.png",
// "images/Selected/emoji-350.png",
// "images/Selected/emoji-351.png",
// "images/Selected/emoji-352.png",
// "images/Selected/emoji-353.png",
// "images/Selected/emoji-354.png",
// "images/Selected/emoji-355.png",
// "images/Selected/emoji-356.png",
// "images/Selected/emoji-357.png",
// "images/Selected/emoji-358.png",
// "images/Selected/emoji-359.png",
// "images/Selected/emoji-360.png",
// "images/Selected/emoji-361.png",
// "images/Selected/emoji-362.png",
// "images/Selected/emoji-363.png",
// "images/Selected/emoji-364.png",
// "images/Selected/emoji-365.png",
// "images/Selected/emoji-366.png",
// "images/Selected/emoji-367.png",
// "images/Selected/emoji-368.png",
// "images/Selected/emoji-369.png",
// "images/Selected/emoji-370.png",
// "images/Selected/emoji-371.png",
// "images/Selected/emoji-372.png",
// "images/Selected/emoji-373.png",
// "images/Selected/emoji-374.png",
// "images/Selected/emoji-375.png",
// "images/Selected/emoji-376.png",
// "images/Selected/emoji-377.png",
// "images/Selected/emoji-378.png",
// "images/Selected/emoji-379.png",
// "images/Selected/emoji-380.png",
// "images/Selected/emoji-381.png",
// "images/Selected/emoji-382.png",
// "images/Selected/emoji-383.png",
// "images/Selected/emoji-384.png",
// "images/Selected/emoji-385.png",
// "images/Selected/emoji-386.png",
// "images/Selected/emoji-387.png",
// "images/Selected/emoji-388.png",
// "images/Selected/emoji-389.png",
// "images/Selected/emoji-390.png",
// "images/Selected/emoji-391.png",
// "images/Selected/emoji-392.png",
// "images/Selected/emoji-393.png",
// "images/Selected/emoji-394.png",
// "images/Selected/emoji-395.png",
// "images/Selected/emoji-396.png",
// "images/Selected/emoji-397.png",
// "images/Selected/emoji-398.png",
// "images/Selected/emoji-399.png",
// "images/Selected/emoji-400.png",
// "images/Selected/emoji-401.png",
// "images/Selected/emoji-402.png",
// "images/Selected/emoji-403.png",
// "images/Selected/emoji-404.png",
// "images/Selected/emoji-405.png",
// "images/Selected/emoji-406.png",
// "images/Selected/emoji-407.png",
// "images/Selected/emoji-408.png",
// "images/Selected/emoji-409.png",
// "images/Selected/emoji-410.png",
// "images/Selected/emoji-411.png",
// "images/Selected/emoji-412.png",
// "images/Selected/emoji-413.png",
// "images/Selected/emoji-414.png",
// "images/Selected/emoji-415.png",
// "images/Selected/emoji-416.png",
// "images/Selected/emoji-417.png",
// "images/Selected/emoji-418.png",
// "images/Selected/emoji-419.png",
// "images/Selected/emoji-420.png",
// "images/Selected/emoji-421.png",
// "images/Selected/emoji-422.png",
// "images/Selected/emoji-423.png",
// "images/Selected/emoji-424.png",
// "images/Selected/emoji-425.png",
// "images/Selected/emoji-426.png",
// "images/Selected/emoji-427.png",
// "images/Selected/emoji-428.png",
// "images/Selected/emoji-429.png",
// "images/Selected/emoji-430.png",
// "images/Selected/emoji-431.png",
// "images/Selected/emoji-432.png",
// "images/Selected/emoji-433.png",
// "images/Selected/emoji-434.png",
// "images/Selected/emoji-435.png",
// "images/Selected/emoji-436.png",
// "images/Selected/emoji-437.png",
// "images/Selected/emoji-438.png",
// "images/Selected/emoji-439.png",
// "images/Selected/emoji-440.png",
// "images/Selected/emoji-441.png",
// "images/Selected/emoji-442.png",
// "images/Selected/emoji-443.png",
// "images/Selected/emoji-444.png",
// "images/Selected/emoji-445.png",
// "images/Selected/emoji-446.png",
// "images/Selected/emoji-447.png",
// "images/Selected/emoji-448.png",
// "images/Selected/emoji-449.png",
// "images/Selected/emoji-450.png",
// "images/Selected/emoji-451.png",
// "images/Selected/emoji-452.png",
// "images/Selected/emoji-453.png",
// "images/Selected/emoji-454.png",
// "images/Selected/emoji-455.png",
// "images/Selected/emoji-456.png",
// "images/Selected/emoji-457.png",
// "images/Selected/emoji-458.png",
// "images/Selected/emoji-459.png",
// "images/Selected/emoji-460.png",
// "images/Selected/emoji-461.png",
// "images/Selected/emoji-462.png",
// "images/Selected/emoji-463.png",
// "images/Selected/emoji-464.png",
// "images/Selected/emoji-465.png",
// "images/Selected/emoji-466.png",
// "images/Selected/emoji-467.png",
// "images/Selected/emoji-468.png",
// "images/Selected/emoji-469.png",
// "images/Selected/emoji-470.png",
// "images/Selected/emoji-471.png",
// "images/Selected/emoji-472.png",
// "images/Selected/emoji-473.png",
// "images/Selected/emoji-474.png",
// "images/Selected/emoji-475.png",
// "images/Selected/emoji-476.png",
// "images/Selected/emoji-477.png",
// "images/Selected/emoji-478.png",
// "images/Selected/emoji-479.png",
// "images/Selected/emoji-480.png",
// "images/Selected/emoji-481.png",
// "images/Selected/emoji-482.png",
// "images/Selected/emoji-483.png",
// "images/Selected/emoji-484.png",
// "images/Selected/emoji-485.png",
// "images/Selected/emoji-486.png",
// "images/Selected/emoji-487.png",
// "images/Selected/emoji-488.png",
// "images/Selected/emoji-489.png",
// "images/Selected/emoji-490.png",
// "images/Selected/emoji-491.png",
// "images/Selected/emoji-492.png",
// "images/Selected/emoji-493.png",
// "images/Selected/emoji-494.png",
// "images/Selected/emoji-495.png",
// "images/Selected/emoji-496.png",
// "images/Selected/emoji-497.png",
// "images/Selected/emoji-498.png",
// "images/Selected/emoji-499.png",
// "images/Selected/emoji-500.png",
// "images/Selected/emoji-501.png",
// "images/Selected/emoji-502.png",
// "images/Selected/emoji-503.png",
// "images/Selected/emoji-504.png",
// "images/Selected/emoji-505.png",
// "images/Selected/emoji-506.png",
// "images/Selected/emoji-507.png",
// "images/Selected/emoji-508.png",
// "images/Selected/emoji-509.png",
// "images/Selected/emoji-510.png",
// "images/Selected/emoji-511.png",
// "images/Selected/emoji-512.png",
// "images/Selected/emoji-513.png",
// "images/Selected/emoji-514.png",
// "images/Selected/emoji-515.png",
// "images/Selected/emoji-516.png",
// "images/Selected/emoji-517.png",
// "images/Selected/emoji-518.png",
// "images/Selected/emoji-519.png",
// "images/Selected/emoji-520.png",
// "images/Selected/emoji-521.png",
// "images/Selected/emoji-522.png",
// "images/Selected/emoji-523.png",
// "images/Selected/emoji-524.png",
// "images/Selected/emoji-525.png",
// "images/Selected/emoji-526.png",
// "images/Selected/emoji-527.png",
// "images/Selected/emoji-528.png",
// "images/Selected/emoji-529.png",
// "images/Selected/emoji-530.png",
// "images/Selected/emoji-531.png",
// "images/Selected/emoji-532.png",
// "images/Selected/emoji-533.png",
// "images/Selected/emoji-534.png",
// "images/Selected/emoji-535.png",
// "images/Selected/emoji-536.png",
// "images/Selected/emoji-537.png",
// "images/Selected/emoji-538.png",
// "images/Selected/emoji-539.png",
// "images/Selected/emoji-540.png",
// "images/Selected/emoji-541.png",
// "images/Selected/emoji-542.png",
// "images/Selected/emoji-543.png",
// "images/Selected/emoji-544.png",
// "images/Selected/emoji-545.png",
// "images/Selected/emoji-546.png",
// "images/Selected/emoji-547.png",
// "images/Selected/emoji-548.png",
// "images/Selected/emoji-549.png",
// "images/Selected/emoji-550.png",
// "images/Selected/emoji-551.png",
// "images/Selected/emoji-552.png",
// "images/Selected/emoji-553.png",
// "images/Selected/emoji-554.png",
// "images/Selected/emoji-555.png",
// "images/Selected/emoji-556.png",
// "images/Selected/emoji-557.png",
// "images/Selected/emoji-558.png",
// "images/Selected/emoji-559.png",
// "images/Selected/emoji-560.png",
// "images/Selected/emoji-561.png",
// "images/Selected/emoji-562.png",
// "images/Selected/emoji-563.png",
// "images/Selected/emoji-564.png",
// "images/Selected/emoji-565.png",
// "images/Selected/emoji-566.png",
// "images/Selected/emoji-567.png",
// "images/Selected/emoji-568.png",
// "images/Selected/emoji-569.png",
// "images/Selected/emoji-570.png",
// "images/Selected/emoji-571.png",
// "images/Selected/emoji-572.png",
// "images/Selected/emoji-573.png",
// "images/Selected/emoji-574.png",
// "images/Selected/emoji-575.png",
// "images/Selected/emoji-576.png",
// "images/Selected/emoji-577.png",
// "images/Selected/emoji-578.png",
// "images/Selected/emoji-579.png",
// "images/Selected/emoji-580.png",
// "images/Selected/emoji-581.png",
// "images/Selected/emoji-582.png",
// "images/Selected/emoji-583.png",
// "images/Selected/emoji-584.png",
// "images/Selected/emoji-585.png",
// "images/Selected/emoji-586.png",
// "images/Selected/emoji-587.png",
// "images/Selected/emoji-588.png",
// "images/Selected/emoji-589.png",
// "images/Selected/emoji-590.png",
// "images/Selected/emoji-591.png",
// "images/Selected/emoji-592.png",
// "images/Selected/emoji-593.png",
// "images/Selected/emoji-594.png",
// "images/Selected/emoji-595.png",
// "images/Selected/emoji-596.png",
// "images/Selected/emoji-597.png",
// "images/Selected/emoji-598.png",
// "images/Selected/emoji-599.png",
// "images/Selected/emoji-600.png",
// "images/Selected/emoji-601.png",
// "images/Selected/emoji-602.png",
// "images/Selected/emoji-603.png",
// "images/Selected/emoji-604.png",
// "images/Selected/emoji-605.png",
// "images/Selected/emoji-606.png",
// "images/Selected/emoji-607.png",
// "images/Selected/emoji-608.png",
// "images/Selected/emoji-609.png",
// "images/Selected/emoji-610.png",
// "images/Selected/emoji-611.png",
// "images/Selected/emoji-612.png",
// "images/Selected/emoji-613.png",
// "images/Selected/emoji-614.png",
// "images/Selected/emoji-615.png",
// "images/Selected/emoji-616.png",
// "images/Selected/emoji-617.png",
// "images/Selected/emoji-618.png",
// "images/Selected/emoji-619.png",
// "images/Selected/emoji-620.png",
// "images/Selected/emoji-621.png",
// "images/Selected/emoji-622.png",
// "images/Selected/emoji-623.png",
// "images/Selected/emoji-624.png",
// "images/Selected/emoji-625.png",
// "images/Selected/emoji-626.png",
// "images/Selected/emoji-627.png",
// "images/Selected/emoji-628.png",
// "images/Selected/emoji-629.png",
// "images/Selected/emoji-630.png",
// "images/Selected/emoji-631.png",
// "images/Selected/emoji-632.png",
// "images/Selected/emoji-633.png",
// "images/Selected/emoji-634.png",
// "images/Selected/emoji-635.png",
// "images/Selected/emoji-636.png",
// "images/Selected/emoji-637.png",
// "images/Selected/emoji-638.png",
// "images/Selected/emoji-639.png",
// "images/Selected/emoji-640.png",
// "images/Selected/emoji-641.png",
// "images/Selected/emoji-642.png",
// "images/Selected/emoji-643.png",
// "images/Selected/emoji-644.png",
// "images/Selected/emoji-645.png",
// "images/Selected/emoji-646.png",
// "images/Selected/emoji-647.png",
// "images/Selected/emoji-648.png",
// "images/Selected/emoji-649.png",
// "images/Selected/emoji-650.png",
// "images/Selected/emoji-651.png",
// "images/Selected/emoji-652.png",
// "images/Selected/emoji-653.png",
// "images/Selected/emoji-654.png",
// "images/Selected/emoji-655.png",
// "images/Selected/emoji-656.png",
// "images/Selected/emoji-657.png",
// "images/Selected/emoji-658.png",
// "images/Selected/emoji-659.png",
// "images/Selected/emoji-660.png",
// "images/Selected/emoji-661.png",
// "images/Selected/emoji-662.png",
// "images/Selected/emoji-663.png",
// "images/Selected/emoji-664.png",
// "images/Selected/emoji-665.png",
// "images/Selected/emoji-666.png",
// "images/Selected/emoji-667.png",
// "images/Selected/emoji-668.png",
// "images/Selected/emoji-669.png",
// "images/Selected/emoji-670.png",
// "images/Selected/emoji-671.png",
// "images/Selected/emoji-672.png",
// "images/Selected/emoji-673.png",
// "images/Selected/emoji-674.png",
// "images/Selected/emoji-675.png",
// "images/Selected/emoji-676.png",
// "images/Selected/emoji-677.png",
// "images/Selected/emoji-678.png",
// "images/Selected/emoji-679.png",
// "images/Selected/emoji-680.png",
// "images/Selected/emoji-681.png",
// "images/Selected/emoji-682.png",
// "images/Selected/emoji-683.png",
// "images/Selected/emoji-684.png",
// "images/Selected/emoji-685.png",
// "images/Selected/emoji-686.png",
// "images/Selected/emoji-687.png",
// "images/Selected/emoji-688.png",
// "images/Selected/emoji-689.png",
// "images/Selected/emoji-690.png",
// "images/Selected/emoji-691.png",
// "images/Selected/emoji-692.png",
// "images/Selected/emoji-693.png",
// "images/Selected/emoji-694.png",
// "images/Selected/emoji-695.png",
// "images/Selected/emoji-696.png",
// "images/Selected/emoji-697.png",
// "images/Selected/emoji-698.png",
// "images/Selected/emoji-699.png",
// "images/Selected/emoji-700.png",
// "images/Selected/emoji-701.png",
// "images/Selected/emoji-702.png",
// "images/Selected/emoji-703.png",
// "images/Selected/emoji-704.png",
// "images/Selected/emoji-705.png",
// "images/Selected/emoji-706.png",
// "images/Selected/emoji-707.png",
// "images/Selected/emoji-708.png",
// "images/Selected/emoji-709.png",
// "images/Selected/emoji-710.png",
// "images/Selected/emoji-711.png",
// "images/Selected/emoji-712.png",
// "images/Selected/emoji-713.png",
// "images/Selected/emoji-714.png",
// "images/Selected/emoji-715.png",
// "images/Selected/emoji-716.png",
// "images/Selected/emoji-717.png",
// "images/Selected/emoji-718.png",
// "images/Selected/emoji-719.png",
// "images/Selected/emoji-720.png",
// "images/Selected/emoji-721.png",
// "images/Selected/emoji-722.png",
// "images/Selected/emoji-723.png",
// "images/Selected/emoji-724.png",
// "images/Selected/emoji-725.png",
// "images/Selected/emoji-726.png",
// "images/Selected/emoji-727.png",
// "images/Selected/emoji-728.png",
// "images/Selected/emoji-729.png",
// "images/Selected/emoji-730.png",
// "images/Selected/emoji-731.png",
// "images/Selected/emoji-732.png",
// "images/Selected/emoji-733.png",
// "images/Selected/emoji-734.png",
// "images/Selected/emoji-735.png",
// "images/Selected/emoji-736.png",
// "images/Selected/emoji-737.png",
// "images/Selected/emoji-738.png",
// "images/Selected/emoji-739.png",
// "images/Selected/emoji-740.png",
// "images/Selected/emoji-741.png",
// "images/Selected/emoji-742.png",
// "images/Selected/emoji-743.png",
// "images/Selected/emoji-744.png",
// "images/Selected/emoji-745.png",
// "images/Selected/emoji-746.png",
// "images/Selected/emoji-747.png",
// "images/Selected/emoji-748.png",
// "images/Selected/emoji-749.png",
// "images/Selected/emoji-750.png",
// "images/Selected/emoji-751.png",
// "images/Selected/emoji-752.png",
// "images/Selected/emoji-753.png"


// 
];
